#!/usr/bin/env python3
"""
extract-everything.py — one-stop Grok setup wizard.

What it does
------------
1. Launches a stealth Chromium (CloakBrowser) so Cloudflare treats us
   as a real user.
2. Navigates to https://grok.com.
3. Waits for YOU to sign in / sign up (interactive — the script
   watches the page state and detects when sso + cf_clearance cookies
   appear).
4. Sends a test chat message to trigger x-statsig-id generation, then
   captures that header from the outgoing request.
5. Decodes the challenge:
       - bytes 0..48  = 49-byte static fingerprint (CHALLENGE_HEADER_HEX)
       - byte  69     = trailer constant                  (CHALLENGE_TRAILER)
6. Pulls all required cookies:
       sso, sso-rw, cf_clearance, __cf_bm
7. Writes a complete .env file (atomic write, chmod 600).
8. Runs a smoke test against the server (start, hit /health, stop).

Usage
-----
    # Live mode — opens a real browser, you sign in, .env gets written
    python scripts/extract-everything.py

    # Test mode — no browser, uses a stubbed session, perfect for CI
    python scripts/extract-everything.py --test

    # Custom env output path
    python scripts/extract-everything.py --env-file /tmp/my.env

    # Skip the smoke test
    python scripts/extract-everything.py --no-smoke

    # Point at a different server during the smoke test
    python scripts/extract-everything.py --server-port 5000

Exit codes
----------
    0  success
    1  user cancelled
    2  cookies not found (login not detected)
    3  challenge extraction failed
    4  .env write failed
    5  smoke test failed
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import signal
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional


# ---------- ANSI colours (no-op when not a tty) ----------

class _C:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RED = "\033[0;31m"
    GREEN = "\033[0;32m"
    YELLOW = "\033[0;33m"
    BLUE = "\033[0;34m"
    CYAN = "\033[0;36m"

def _supports_color() -> bool:
    return sys.stdout.isatty()

def _c(code: str, text: str) -> str:
    return f"{code}{text}{_C.RESET}" if _supports_color() else text

def info(msg: str) -> None:
    print(_c(_C.BLUE, "ℹ ") + msg)
def ok(msg: str) -> None:
    print(_c(_C.GREEN, "✓ ") + msg)
def warn(msg: str) -> None:
    print(_c(_C.YELLOW, "⚠ ") + msg, file=sys.stderr)
def err(msg: str) -> None:
    print(_c(_C.RED, "✗ ") + msg, file=sys.stderr)
def step(msg: str) -> None:
    print(_c(_C.BOLD + _C.CYAN, f"\n▶ {msg}"))


# ---------- Data classes ----------

@dataclass
class GrokSession:
    """All the data the script extracts from the browser."""
    sso: Optional[str] = None
    sso_rw: Optional[str] = None
    cf_clearance: Optional[str] = None
    cf_bm: Optional[str] = None
    challenge_header_hex: Optional[str] = None
    challenge_trailer: Optional[int] = None
    user_id: Optional[str] = None
    raw_cookies: Dict[str, str] = field(default_factory=dict)

    @property
    def is_auth_complete(self) -> bool:
        return bool(self.sso and self.sso_rw and self.cf_clearance)

    @property
    def is_challenge_complete(self) -> bool:
        return bool(self.challenge_header_hex and self.challenge_trailer is not None)

    @property
    def is_complete(self) -> bool:
        return self.is_auth_complete and self.is_challenge_complete

    def missing(self) -> List[str]:
        out = []
        if not self.sso:
            out.append("sso")
        if not self.sso_rw:
            out.append("sso-rw")
        if not self.cf_clearance:
            out.append("cf_clearance")
        if not self.challenge_header_hex:
            out.append("CHALLENGE_HEADER_HEX")
        if self.challenge_trailer is None:
            out.append("CHALLENGE_TRAILER")
        return out

    def to_env(self) -> str:
        """Render the full .env file content."""
        lines = [
            "# Generated by extract-everything.py",
            "# DO NOT COMMIT THIS FILE — it contains your Grok session.",
            "",
            f"GROK_SSO_COOKIE={self.sso or ''}",
            f"GROK_SSO_RW_COOKIE={self.sso_rw or ''}",
            f"GROK_CF_CLEARANCE={self.cf_clearance or ''}",
            f"GROK_CF_BM={self.cf_bm or ''}",
            "",
            f"CHALLENGE_HEADER_HEX={self.challenge_header_hex or ''}",
            f"CHALLENGE_TRAILER={self.challenge_trailer if self.challenge_trailer is not None else 3}",
            "",
            "PORT=4982",
            "HOST=0.0.0.0",
            "LOG_LEVEL=INFO",
            "RATE_LIMIT_ENABLED=true",
            "RATE_LIMIT_WINDOW_SECONDS=60",
            "RATE_LIMIT_MAX_REQUESTS=20",
            "",
            "GROK_BASE_URL=https://grok.com",
            "GROK_ORIGIN=https://grok.com",
        ]
        if self.user_id:
            lines.append(f"# x-userid (informational only): {self.user_id}")
        return "\n".join(lines) + "\n"


# ---------- Challenge decoder ----------

class ChallengeError(Exception):
    pass


def decode_x_statsig_id(header_value: str) -> tuple[str, int]:
    """Decode an x-statsig-id header into (header_hex, trailer).

    Format (70 bytes total, base64-encoded):
      [0..48]   static 49-byte fingerprint -> CHALLENGE_HEADER_HEX
      [49..68]  per-request random nonce (XOR-padded, we ignore)
      [69]      constant trailer byte     -> CHALLENGE_TRAILER

    Returns:
        (header_hex_98_chars, trailer_int_0_to_255)

    Raises:
        ChallengeError: if the header is malformed.
    """
    if not header_value:
        raise ChallengeError("empty header")

    try:
        raw = base64.b64decode(header_value, validate=True)
    except Exception as e:
        raise ChallengeError(f"not valid base64: {e}") from e

    if len(raw) != 70:
        raise ChallengeError(
            f"expected 70 bytes after base64 decode, got {len(raw)}. "
            "Grok may have changed the wire format — please re-run."
        )

    fingerprint = raw[:49]
    trailer = raw[69]

    return fingerprint.hex(), trailer


# ---------- Cookie capture helpers ----------

COOKIE_NAMES_REQUIRED = ("sso", "sso-rw", "cf_clearance")
COOKIE_NAMES_OPTIONAL = ("__cf_bm", "x-userid", "grok_device_id")

def session_from_cookies(cookies: List[Dict[str, Any]]) -> GrokSession:
    """Build a GrokSession from a list of Playwright cookie dicts."""
    raw = {c["name"]: c["value"] for c in cookies}
    return GrokSession(
        sso=raw.get("sso"),
        sso_rw=raw.get("sso-rw"),
        cf_clearance=raw.get("cf_clearance"),
        cf_bm=raw.get("__cf_bm"),
        user_id=raw.get("x-userid"),
        raw_cookies=raw,
    )


# ---------- Browser driver (live mode) ----------

def launch_browser() -> Any:
    """Launch CloakBrowser + Playwright. Returns the browser object."""
    import os
    import cloakbrowser  # type: ignore

    # The sandbox (and many corporate networks) intercept TLS with a
    # custom CA. Pass the relevant env vars and Chromium flags so the
    # browser can actually reach grok.com.
    ca = (
        os.environ.get("SSL_CERT_FILE")
        or os.environ.get("REQUESTS_CA_BUNDLE")
        or os.environ.get("CURL_CA_BUNDLE")
        or "/etc/ssl/certs/agent-identity/sandbox-gateway-ca.crt"
    )
    args = [
        "--ignore-certificate-errors",
        f"--ssl-client-cert-file={ca}",
    ]
    env = {
        "SSL_CERT_FILE": ca,
        "CURL_CA_BUNDLE": ca,
        "REQUESTS_CA_BUNDLE": ca,
        "CLOAKBROWSER_SUPPRESS_FONT_WARNING": "1",
    }

    # humanize=True so the browser emits real mouse movements, scroll
    # events, and keypress timings. Cloudflare watches all of these.
    return cloakbrowser.launch(
        headless=False,  # interactive — user needs to see the page
        humanize=True,
        args=args,
        env=env,
    )


def wait_for_login(page: Any, timeout_s: int = 600) -> GrokSession:
    """Block until the user has logged in. Returns the cookies.

    Polls the browser's cookies every 2 seconds. Returns when sso,
    sso-rw, AND cf_clearance are all present (login complete + CF
    challenge solved).
    """
    step(f"Waiting for you to sign in (timeout {timeout_s}s)…")
    print(_c(_C.DIM, "  Sign up with your phone number if you don't have an account."))
    print(_c(_C.DIM, "  The script watches for sso + cf_clearance cookies — no need to press anything."))
    print()

    deadline = time.time() + timeout_s
    last_status = ""
    while time.time() < deadline:
        try:
            cookies = page.context.cookies()
            session = session_from_cookies(cookies)
            status = (
                f"sso={'✓' if session.sso else '·'}  "
                f"sso-rw={'✓' if session.sso_rw else '·'}  "
                f"cf_clearance={'✓' if session.cf_clearance else '·'}"
            )
            if status != last_status:
                print(_c(_C.DIM, f"  status: {status}"))
                last_status = status
            if session.is_auth_complete:
                return session
        except Exception as e:
            warn(f"cookie poll failed: {e}")
        time.sleep(2)

    # One last poll, but we already know it's incomplete.
    cookies = page.context.cookies()
    return session_from_cookies(cookies)


def trigger_and_capture_challenge(page: Any, timeout_s: int = 60) -> tuple[str, int]:
    """Send a throwaway chat message and capture the x-statsig-id header.

    The script types a short message into the Grok chat input, sends it,
    and reads the intercepted x-statsig-id header from the outgoing
    /rest/app-chat request.
    """
    step("Triggering a chat message to capture the anti-bot challenge…")

    captured: List[str] = []

    def hook(route: Any, request: Any) -> Any:
        # Capture x-statsig-id from any POST to the chat endpoint.
        if request.method == "POST" and "/rest/app-chat" in request.url:
            sig = request.headers.get("x-statsig-id")
            if sig:
                captured.append(sig)
                # Don't actually send — abort so we don't waste Grok quota.
                route.abort()
                return
        route.continue_()

    page.route("**/rest/app-chat/**", hook)

    try:
        # Try common Grok input selectors. Different builds use different
        # textareas, so we try a few in order.
        input_selectors = [
            'textarea[placeholder*="Ask"]',
            'textarea[placeholder*="Message"]',
            'textarea[placeholder*="anything"]',
            'textarea',
            '[contenteditable="true"]',
            'div[role="textbox"]',
        ]
        sent = False
        for sel in input_selectors:
            try:
                el = page.locator(sel).first
                if el.count() and el.is_visible():
                    el.click()
                    el.fill("ping")
                    # Press Enter to send
                    page.keyboard.press("Enter")
                    sent = True
                    info(f"sent ping via {sel}")
                    break
            except Exception:
                continue

        if not sent:
            warn("could not find Grok chat input — falling back to direct fetch")
            # Fall back to a direct POST from the page context — the
            # browser will attach the right x-statsig-id naturally.
            page.evaluate(
                """
                fetch('https://grok.com/rest/app-chat/conversations/new', {
                    method: 'POST',
                    headers: {'content-type': 'application/json'},
                    body: JSON.stringify({
                        temporary: true,
                        modelName: 'auto',
                        message: 'ping',
                        fileAttachments: [],
                        imageAttachments: [],
                        disableSearch: false,
                        enableImageGeneration: false,
                        returnImageBytes: false,
                        returnRawGrokInXaiRequest: false,
                        enableImageStreaming: false,
                        imageGenerationCount: 0,
                        forceConcise: false,
                        toolOverrides: {},
                        enableSideBySide: true,
                        isAsyncChat: true,
                        webpageUrls: null,
                    }),
                }).catch(() => {});
                """
            )

        # Wait for the captured header to arrive.
        deadline = time.time() + timeout_s
        while time.time() < deadline and not captured:
            page.wait_for_timeout(500)

        if not captured:
            raise ChallengeError(
                "no x-statsig-id captured within timeout. "
                "Try clicking around the chat UI manually and re-run with --no-challenge-timeout."
            )

        return decode_x_statsig_id(captured[0])
    finally:
        try:
            page.unroute("**/rest/app-chat/**")
        except Exception:
            pass


# ---------- .env writer ----------

def write_env_atomic(path: Path, content: str) -> None:
    """Write .env atomically and chmod 600."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=path.parent, prefix=".env.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp_path, path)
        os.chmod(path, 0o600)
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise


# ---------- Smoke test ----------

def run_smoke_test(env_file: Path, port: int) -> bool:
    """Start the server with the given env and check /health."""
    step(f"Running smoke test on port {port}…")

    # Start uvicorn in the background.
    env = os.environ.copy()
    # Strip any existing GROK_* vars so the .env file is the only source.
    for k in list(env.keys()):
        if k.startswith(("GROK_", "CHALLENGE_", "PORT", "RATE_LIMIT_", "LOG_")):
            env.pop(k, None)
    # Load the .env file by running it through Python's parser.
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip().strip('"').strip("'")

    cmd = [
        sys.executable, "-m", "uvicorn", "main:app",
        "--host", "127.0.0.1",
        "--port", str(port),
        "--log-level", "warning",
    ]
    proc = subprocess.Popen(
        cmd,
        cwd=str(env_file.parent.parent),  # project root
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        # Give uvicorn a moment to start.
        time.sleep(2.5)

        import urllib.request
        import urllib.error

        # Hit /health.
        try:
            resp = urllib.request.urlopen(f"http://127.0.0.1:{port}/health", timeout=8)
            body = resp.read().decode()
            print(f"  GET /health -> {resp.status}  body={body[:200]}")
            if resp.status == 200:
                ok("health check passed")
            else:
                warn(f"health returned {resp.status} — cookies may need refresh")
        except urllib.error.HTTPError as e:
            warn(f"health returned HTTP {e.code} — cookies may be stale, but server is up")
        except Exception as e:
            err(f"health check failed: {e}")
            return False

        # Hit /v1/models.
        try:
            resp = urllib.request.urlopen(f"http://127.0.0.1:{port}/v1/models", timeout=8)
            body = resp.read().decode()
            if '"grok-auto"' in body:
                ok("/v1/models lists models")
            else:
                warn(f"/v1/models returned unexpected body: {body[:200]}")
        except Exception as e:
            warn(f"/v1/models check failed: {e}")

        return True
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=3)
        except subprocess.TimeoutExpired:
            proc.kill()


# ---------- Test mode (no real browser) ----------

def run_test_mode(env_file: Path) -> int:
    """Run the script's pure-Python logic against a stubbed session.
    Used by the unit test suite — and by anyone who wants to dry-run
    the wizard without a browser.
    """
    step("Running in TEST mode (no browser)…")

    # A synthetic session that would come out of a real login.
    synthetic = GrokSession(
        sso="test_sso_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdGVzIjp0cnVlfQ.test",
        sso_rw="test_sso_rw_eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdGVzIjp0cnVlfQ.test",
        cf_clearance="Ab3x_test_clearance_token_12345",
        cf_bm="M8Fho70uXwD9FR1LNuA2XuzE9zovx.BolznduoE59dw-test",
        user_id="9ee508b2-9f39-4140-a59a-8ffc299e27f2",
        challenge_header_hex="01" * 49,
        challenge_trailer=3,
    )

    print(f"  synthetic session: complete={synthetic.is_complete}, missing={synthetic.missing()}")

    # Render + write
    content = synthetic.to_env()
    try:
        write_env_atomic(env_file, content)
        ok(f"wrote {env_file} (chmod 600)")
    except Exception as e:
        err(f"failed to write {env_file}: {e}")
        return 4

    # Verify
    written = env_file.read_text()
    for k in ("GROK_SSO_COOKIE", "GROK_SSO_RW_COOKIE", "GROK_CF_CLEARANCE",
              "GROK_CF_BM", "CHALLENGE_HEADER_HEX", "CHALLENGE_TRAILER"):
        if k not in written:
            err(f"missing {k} in written .env")
            return 4
    ok("all required keys present in .env")
    return 0


# ---------- Main flow ----------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="One-stop Grok setup wizard. Launches a stealth browser, "
                    "waits for you to log in, then writes .env and runs a smoke test.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--env-file", type=Path, default=Path(".env"),
                        help="Path to write the .env file (default: .env)")
    parser.add_argument("--test", action="store_true",
                        help="Run in test mode (no browser) — writes a stub .env")
    parser.add_argument("--no-smoke", action="store_true",
                        help="Skip the post-write server smoke test")
    parser.add_argument("--server-port", type=int, default=4984,
                        help="Port to use for the smoke test (default: 4984)")
    parser.add_argument("--login-timeout", type=int, default=600,
                        help="Seconds to wait for you to log in (default: 600 = 10 min)")
    parser.add_argument("--challenge-timeout", type=int, default=60,
                        help="Seconds to wait for x-statsig-id capture (default: 60)")
    args = parser.parse_args()

    if args.test:
        return run_test_mode(args.env_file)

    # ----- Live mode -----
    step("Launching stealth browser (CloakBrowser)…")
    try:
        browser = launch_browser()
    except Exception as e:
        err(f"failed to launch browser: {e}")
        return 1

    page = None
    try:
        page = browser.new_page()
        step("Navigating to https://grok.com…")
        page.goto("https://grok.com", timeout=30000, wait_until="domcontentloaded")
        ok("page loaded")

        # Wait for login
        session = wait_for_login(page, timeout_s=args.login_timeout)
        if not session.is_auth_complete:
            err(f"login timed out — missing: {session.missing()}")
            err("Tips: ")
            err("  - Make sure you completed the SMS verification")
            err("  - Make sure you're not in incognito (some modes skip cf_clearance)")
            err("  - Check that you don't have privacy extensions stripping cookies")
            return 2

        ok(f"got auth cookies: {sorted(session.raw_cookies.keys())[:8]}…")

        # Capture the challenge
        try:
            header_hex, trailer = trigger_and_capture_challenge(
                page, timeout_s=args.challenge_timeout,
            )
        except ChallengeError as e:
            err(f"failed to capture challenge: {e}")
            return 3

        session.challenge_header_hex = header_hex
        session.challenge_trailer = trailer
        ok(f"got challenge: header={len(header_hex)//2} bytes, trailer={trailer}")

        # Refresh cookies (cf_bm may have rotated during the chat attempt)
        cookies = page.context.cookies()
        session = session_from_cookies(cookies)
        session.challenge_header_hex = header_hex
        session.challenge_trailer = trailer
        if not session.cf_bm:
            warn("__cf_bm not present (optional)")

        # Write .env
        step(f"Writing {args.env_file}…")
        try:
            write_env_atomic(args.env_file, session.to_env())
        except Exception as e:
            err(f"failed to write .env: {e}")
            return 4
        ok(f"wrote {args.env_file} (chmod 600)")

        # Smoke test
        if not args.no_smoke:
            run_smoke_test(args.env_file, args.server_port)
        else:
            info("smoke test skipped (--no-smoke)")

        ok("All done! Run: docker compose up -d --build  (or: python main.py)")
        return 0

    except KeyboardInterrupt:
        warn("cancelled by user")
        return 1
    finally:
        try:
            if page is not None:
                page.close()
        except Exception:
            pass
        try:
            browser.close()
        except Exception:
            pass


if __name__ == "__main__":
    sys.exit(main())
